### ISSUE TITLE
Decoding reads more bytes than necessary?

### ISSUE THREAD

**Issue by NicolasBuecher** [mdouchement/hdr#28]
Hello and thanks for your work,

I wanted to encode several HDR images into one buffer or file but then `rgbe.Decode` seems to read more bytes than it should and I can't figure why after reviewing your code.

Encoding and decoding once works fine though.

This, for instance, will throw an error:
```
rgbe.Encode(buf, img)
rgbe.Encode(buf, img)
img, e := rgbe.Decode(buf)
img, e = rgbe.Decode(buf)
```

More verbose:
```
// Encode twice the HDR image and check how many bytes were written
rgbe.Encode(buf, img)
rgbe.Encode(buf, img)
writtenBytes := buf.Len()

// No problem, the first img is fine
img, e := rgbe.Decode(buf)

// More bytes read than written though
fmt.Printf("Bytes read: %v; Bytes written: %v", writtenBytes - buf.Len(), writtenBytes)

// And this returns an invalid format error because we begin to read too far in the buffer
img, e = rgbe.Decode(buf)
if e != nil {
    log.Fatal(e)
}
```

Any idea why?

**Comment by mdouchement** [comment]
Hello, I think it's because `rgbe.Decode` uses a `bufio.NewReader` with a buffer of 4096 bytes. The next image has been partially read during the decoding of the first image.
Decoder assumes that only one image is read.

Alternatively, you can use a `bytes.Reader` that is seeckable:
```go
package main

import (
	"bytes"
	"image"
	"io"
	"os"

	"github.com/mdouchement/hdr"
	"github.com/mdouchement/hdr/codec/rgbe"
)

func main() {
	f, err := os.Open("memorial_o876.hdr")
	check(err)
	defer f.Close()

	m, _, err := image.Decode(f)
	check(err)

	img := m.(hdr.Image)

	var buf bytes.Buffer
	err = rgbe.Encode(&buf, img)
	check(err)

	n := buf.Len()

	err = rgbe.Encode(&buf, img)
	check(err)

	r := bytes.NewReader(buf.Bytes())

	_, err = rgbe.Decode(r)
	check(err)

	_, err = r.Seek(int64(n), io.SeekStart) // Set the start of the second image
	check(err)

	_, err = rgbe.Decode(r)
	check(err)
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
```

**Comment by NicolasBuecher** [comment]
Oh god, I didn't expect a response so fast and so complete. 

That was how I intended to go through the issue, but I couldn't sleep without understanding why I had to do that.

Thank you very much for your time!
